# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test3(self):
    self.driver.get("http://demo-store.seleniumacademy.com/")
    self.driver.set_window_size(974, 1032)
    self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(2) .product-name > a").click()
    self.driver.find_element(By.CSS_SELECTOR, "#swatch21 img").click()
    self.driver.find_element(By.CSS_SELECTOR, "#swatch78 > .swatch-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-cart:nth-child(1)").click()
    product_price = self.driver.find_element(By.CSS_SELECTOR, ".product-cart-price .price").text
    element = self.driver.find_element(By.CSS_SELECTOR, ".product-cart-price .price")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    price_chart_1 = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > .a-right > .price").text
    price_chart_2 = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .price").text
    price_chart_3 = self.driver.find_element(By.CSS_SELECTOR, "strong > .price").text

    assert product_price == price_chart_1

    price_chart_1 = float(price_chart_1[1:])
    price_chart_2 = float(price_chart_2[1:])
    price_chart_3 = float(price_chart_3[1:])

    assert price_chart_3 == round(price_chart_1 + price_chart_2, 2)


  
