# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("http://demo-store.seleniumacademy.com/")
    self.driver.set_window_size(974, 1032)
    self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(1) .product-name > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".toggle-tabs > li:nth-child(2) > span").click()
    time.sleep(2)
    occasion = self.driver.find_element(By.CSS_SELECTOR, ".first > .data").text
    assert occasion == "Casual"
    type = self.driver.find_element(By.CSS_SELECTOR, ".even > .data").text
    assert type == "Tees"
    gender = self.driver.find_element(By.CSS_SELECTOR, ".last > .data").text
    assert gender == "Male"
  
